### ISSUE TITLE
Retrieve the "password data" of a Windows instance

### ISSUE THREAD

**Issue by le-garff-yoann** [outscale-dev/terraform-provider-outscale#15]
The Terraform provider for AWS allows me to retrieve password data of a Windows instance this way: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#get_password_data

Is it possible to implement the same thing for Outscale?

**Comment by outscale-mgo** [comment]
Hello,

We actually have an `admin_password` field in our resource.
The "problem" is that CreateVms return before the VM have been fully set up.
so when creating a vm windows resource, the resource will always  have no  `admin_password` at first, and need manual refresh using `terraform apply`, in order to obtain the password.

**Comment by outscale-mgo** [comment]
`admin_password` been already here as a replacement for `get_password_data`, I close the issue, if you still have trouble, don't hesitate to reopen.

**Comment by le-garff-yoann** [comment]
Ok, thx. I will test that!
