### ISSUE TITLE
Open HTTPS flow for Floating virtual IP (VIP)  of Keepalived loadbalancer 

### ISSUE THREAD

**Issue by boussoufiane** [outscale-dev/terraform-provider-outscale#152]
Hi ,

I need to implement the loadbalancer failover with Floating virtual IP (VIP)  with Keepalived and Ha proxy .

![image](https://user-images.githubusercontent.com/11522624/182875711-ac60308b-7def-4198-8e2d-f131d886bf1d.png)

keepalived create  and attach dynamically the VIP ( for ex 10.0.13.88/32) to the haproxy master instance . if there is an issue in this instance it attach the VIP to the backup instance

The problem is how to open flow to this VIP in outscale ?

I tried to create a FNI in outscale  with same IP as the VIP and  HTTPS Security groups without attaching it to any instances  but 
it is not working (time out ).

If i attach this FNI to one Haproxy instance , all traffic is using this instance and the seconde instance is never used  

For me creating a FNI with SG without attaching it to any instance seems to me the closest approach to open flow.

So the question here is how to open flows (HTTPS access ) to this VIP that was created by keepalived and not outscale .

### Terraform Version
 ``` 
 v1.1.7
```

### outscale-dev/outscale
 ``` 
0.5.3
```

**Comment by outscale-toa** [comment]
Hello @boussoufiane ,

Thanks for reaching us, we are looking at your issue

Best regards,

**Comment by jerome-jutteau** [comment]
Hi @boussoufiane, as I understand it, you would like to be able to move some IP from an [Instance](https://docs.outscale.com/en/userguide/About-Instances.html) to another.
This could be done by either:
- Detaching an [Elastic IP](https://docs.outscale.com/en/userguide/About-EIPs.html) from one Instance and attach it to an other Instance, or...
- Detaching an [Flexible Network Interface](https://docs.outscale.com/en/userguide/About-FNIs.html) from an Instance and attach it to an other Instance. Note that you can [assign](https://docs.outscale.com/fcu#assignprivateipaddresses) one or more secondary private ip addresses.

> So the question here is how to open flows (HTTPS access ) to this VIP that was created by keepalived and not outscale .

In most case network traffic is protected by default using [Security Groups](https://docs.outscale.com/en/userguide/About-Security-Groups.html). Without attaching a security group and adding the proper rules, you would probably not access the service.

For more details about cloud concepts, we would recommend you to check [Outscale Documentation](https://docs.outscale.com/en/userguide/Home.html), contact support team in case of IaaS issue or contact your pre-sales consultant. For more details about what can be done with terraform, please check [terraform documentation](https://registry.terraform.io/providers/outscale-dev/outscale/latest/docs) and [examples](https://github.com/outscale-dev/terraform-provider-outscale/tree/master/examples).

In order to be able to help you specifically with Terraform plugin, we would need you to fill the specific informations asked in bug template (when creating an issue). You can either close this issue, edit this one or create a new one.
